### ISSUE TITLE
Double Chat Room when clicking chat now after match

### ISSUE THREAD

**Issue by matchaDateFinder** [matchaDateFinder/matchaMobileApplication#1]
Two chat room is generated for a single pair of users when clicking "chat now" after both parties accept the match

Steps to reproduce
1. have two accounts
2. first account find match and accept
3. second account find the first account and accept
4. second account taps on "chat now"
5. in the chat area there are two chat room instead of one

**Comment by wuryantoAji** [comment]
Turns out this is caused by manipulating the data and makes the user find the same match.
e.g.
Joni already got matched to Mawar and both react with "yes".
In the DB, dev changed the data to check a feature such as make as if Joni haven't got matched to Mawar and react "yes" again to the match.
